CREATE DATABASE festivities;
CREATE TABLE FESTIVITIE
(
	FTE_NAME VARCHAR(80),
    FTE_PLACE VARCHAR(80),
    FTE_START DATETIME,
    FTE_END DATETIME,
    CONSTRAINT PRIMARY KEY (FTE_NAME)
);
